// FILE: ./aznavrail/src/main/java/com/hereliesaz/aznavrail/AzActivity.kt
package com.hereliesaz.aznavrail

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.enableEdgeToEdge

/**
 * Interface representing the generated navigation graph.
 *
 * This interface is implemented by the code generated by the AzNavRail KSP processor.
 * It encapsulates the setup and execution of the AzNavRail UI structure.
 */
interface AzGraphInterface {
    /**
     * Executes the graph, setting the content of the activity.
     *
     * @param activity The host [ComponentActivity].
     */
    fun Run(activity: ComponentActivity)
}

/**
 * The base class for Activities using the High-Inference AzNavRail system.
 *
 * Extending this class allows the KSP processor to automatically generate the navigation graph
 * and wiring based on `@Az` annotations. It handles `onCreate` and edge-to-edge setup automatically.
 *
 * To use this:
 * 1. Extend [AzActivity].
 * 2. Annotate your class and methods with `@Az`.
 * 3. Point the abstract `graph` property to the generated `AzGraph` object (e.g., `MyActivityAzGraph`).
 */
abstract class AzActivity : ComponentActivity() {
    /**
     * The generated graph object. This must be assigned the generated `AzGraph` instance.
     */
    abstract val graph: AzGraphInterface

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        graph.Run(this)
    }

    /**
     * Optional override to inject dynamic runtime configuration into the rail.
     *
     * This function is called within the [AzNavRailScope] during graph execution, allowing
     * you to modify configuration, theme, or add dynamic items programmatically alongside
     * the static annotated structure.
     */
    open fun AzNavRailScope.configureRail() {
        // Optional override for dynamic configuration
    }
}