package com.hereliesaz.aznavrail

import android.os.Bundle
import androidx.activity.ComponentActivity
import com.hereliesaz.aznavrail.annotation.Az

/**
 * Base abstract activity for AzNavRail applications using annotation processing.
 *
 * This class serves as the entry point for applications that use the `@Az` annotation
 * to generate their navigation graph. It automatically executes the generated graph
 * setup in [onCreate].
 *
 * Extending classes must provide an instance of the generated [AzGraphInterface] (usually named `AzGraph`).
 */
abstract class AzActivity : ComponentActivity() {

    /**
     * The generated graph interface instance.
     * This is typically the object generated by the KSP processor (e.g., `AzGraph`).
     */
    abstract val graph: AzGraphInterface

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        graph.run(this)
    }
}
