package com.hereliesaz.aznavrail

import androidx.activity.ComponentActivity

/**
 * Interface generated by the annotation processor to initialize the navigation graph.
 *
 * Implementations of this interface are automatically generated and used to set up the [AzNavRail]
 * content within the activity's `onCreate` method.
 */
interface AzGraphInterface {
    /**
     * Executes the graph setup logic.
     *
     * @param activity The host activity.
     */
    fun run(activity: ComponentActivity)
}
