package com.hereliesaz.aznavrail.tutorial

import androidx.compose.runtime.Composable

/**
 * Reactive, status-driven guidance model — the replacement for the scripted scene/card tutorial.
 *
 * The app (and AzNavHost automatically) describe the userflow as a flowchart of **statuses** (nodes)
 * and **edges** (transitions, each carrying the instruction to traverse it). The developer declares
 * one or more **goals** (target statuses) and activates them; the engine ([AzStatusEngine]) observes
 * which statuses are currently true and always shows the instruction to reach the next status on the
 * path toward each active goal, auto-advancing the instant a target status becomes true.
 *
 * A "status" is just a `String` id, resolved uniformly by the engine from three sources:
 *  - a developer predicate registered via `azStatus(id) { … }`,
 *  - an active classifier name (true while it is in `activeClassifiers`),
 *  - a built-in `az.*` id published by AzNavHost from the rail/host/route/onscreen/sheet state.
 */

/** What a guidance instruction spotlights. Reused by the highlight renderer. */
sealed interface AzGuideHighlight {
    /** No spotlight; the instruction card floats over a plain dim. */
    data object None : AzGuideHighlight
    /** Dim the whole screen with no punch-out. */
    data object FullScreen : AzGuideHighlight
    /** Spotlight the rail item with this id (looked up in `itemBoundsCache`). */
    data class Item(val id: String) : AzGuideHighlight
    /** Spotlight an explicit window-space rectangle. */
    data class Area(val left: Float, val top: Float, val width: Float, val height: Float) : AzGuideHighlight
}

/**
 * The instruction shown while the user traverses one edge: the prompt text, an optional title, what to
 * spotlight, and optional inline media.
 *
 * The instruction is rendered as a **callout positioned adjacent to its [highlight] target** — next to
 * the control the user would use to accomplish that hop — not as a centered card. When several goals
 * are active, **every** active instruction is shown at once, each placed by its own target, so the
 * user sees, in place, how to accomplish each goal. [side] biases which edge of the target the callout
 * prefers (auto-resolved against screen bounds when [AzCalloutSide.Auto]).
 */
data class AzInstruction(
    val text: String,
    val title: String? = null,
    val highlight: AzGuideHighlight = AzGuideHighlight.None,
    val side: AzCalloutSide = AzCalloutSide.Auto,
    val media: (@Composable () -> Unit)? = null,
)

/** Preferred placement of a callout relative to its highlight target. */
enum class AzCalloutSide { Auto, Above, Below, Start, End }

/**
 * One edge of the flowchart: while status [from] is true, performing the [instruction] is expected to
 * make status [to] true (an interactive hop). A passive edge ([to] == `null`) just shows info while
 * [from] holds. Authored via `azEdge(...)`, or auto-generated by AzNavHost for rail affordances.
 */
data class AzEdge(
    val from: String,
    val to: String?,
    val instruction: AzInstruction,
)

/**
 * A developer-declared guidance target. The engine routes from the current status toward [target]; the
 * developer activates/deactivates goals on the controller (several may guide at once). When
 * [autoStartWhen] is non-null the goal self-activates once that status becomes true (onboarding-style).
 *
 * When several active goals are guiding at once, **every** goal's next-hop instruction is shown
 * simultaneously, each as a callout placed adjacent to its own target (deduped where two goals share
 * the exact same next hop). No goal's instruction ever suppresses another's.
 */
data class AzGoal(
    val id: String,
    val target: String,
    val label: String? = null,
    val autoStartWhen: String? = null,
)

